### ISSUE TITLE
Disabling the extension from safari

### ISSUE THREAD

**Issue by alhay491** [ulyngs/open-source-no-distractions-for-youtube#6]
On my iPhone when I try and temporarily allow recommended videos or up next it does not work. On my iPad when I open the extension in safari it has 5 boxes some are repeats. The top 3 boxes don’t work but the bottom 2 allow me to see recommended videos and up next videos.

**Comment by ulyngs** [comment]
Thanks for flagging this!

Can you let me know which model iPhone and iPad you use, and which iOS version they run? Also, could you share a screenshot of the repeated boxes on iPad?

**Comment by ulyngs** [comment]
Thanks for this, I am able to reproduce the problem in the XCode device simulator.

I will fix this an submit an updated version to the App Store this week - thanks for your patience!

**Comment by ulyngs** [comment]
I have fixed the issue and submitted an update to the App Store - it should be available within the next week, depending on how speedily Apple reviews the update! :)

**Comment by ulyngs** [comment]
The updated version is now available on the App Store - could you update and let me know if this solved the issue?

**Comment by alhay491** [comment]
Hi thanks for being so quick on this.
The iPad working perfectly now.
The phone still doesn’t show videos when I check the boxes. Tried restarting the phone and redownloading the app and still no luck. Not sure what other information to provide to debug.
Also the reason I got the app was to not show the videos so in a way this is good for me. Happy to help test if you have suggestions or trials to do.
Cheers

**Comment by ulyngs** [comment]
Hmmm that's strange - on the XCode simulator, it seems to work well on iPhone 12 Pro, and it also works fine for me on my actual iPhone 13 mini.

Not sure what the issue is - when you are on the front page of youtube, and the videos are blank, then they do not appear when you toggle them on by tapping aA -> 'No Distractions' for YouTube -> Recommended videos?

**Comment by alhay491** [comment]
I have attached a screenshot
When I do the same on my iPad then the videos show up.
If I close the screen and reopen it then the box is unchecked.
![874D1C89-96F0-4C3C-90AF-5844564FFAB7](https://user-images.githubusercontent.com/8901927/149583501-7c97cc44-5893-4976-8c0a-a31bc85f0809.png)

**Comment by ulyngs** [comment]
That's really bizarre, I'll see if it comes up for other users and try to figure out what's causing it!

**Comment by alhay491** [comment]
Sounds good
Thanks for looking into this

**Comment by ulyngs** [comment]
@alhay491  can you try updating to the latest version and let me know if you still have issues?

**Comment by alhay491** [comment]
It is fixed now! Thank you very much!

**Comment by ulyngs** [comment]
marvellous!
